/**
 * List of common disposable/temporary email providers
 * This is a basic list - in production, consider using a service like:
 * - https://www.npmjs.com/package/disposable-email-domains
 * - https://github.com/disposable-email-domains/disposable-email-domains
 */
const DISPOSABLE_DOMAINS = new Set([
  // Temporary email services
  "tempmail.com",
  "temp-mail.org",
  "throwaway.email",
  "guerrillamail.com",
  "mailinator.com",
  "10minutemail.com",
  "yopmail.com",
  "fakeinbox.com",
  "trashmail.com",
  "maildrop.cc",
  "sharklasers.com",
  "spam4.me",
  "temp-mail.io",
  "tempmail.io",
  "mailtrap.io",
  "ethereal.email",
  "mailnesia.com",
  "temp-mail.dev",
  "temporary-mail.net",
  "throwawaymail.com",
  "guerrillamail.info",
  "mailnesia.com",
  "mintemail.com",
  "mytrashmail.com",
  "temp-mail.co",
  "tempmail.net",
  "tempmail.us",
  "temp-mail.net",
  "maildrop.cc",
  "mailnesia.com",
  "temp-mail.de",
  "temp-mail.fr",
  "temp-mail.es",
  "temp-mail.it",
  "temp-mail.pt",
  "temp-mail.ru",
  "temp-mail.ua",
  "temp-mail.jp",
  "temp-mail.cn",
  "temp-mail.kr",
  "temp-mail.in",
  "temp-mail.br",
  "temp-mail.mx",
  "temp-mail.ar",
  "temp-mail.za",
  "temp-mail.au",
  "temp-mail.nz",
  "temp-mail.sg",
  "temp-mail.my",
  "temp-mail.th",
  "temp-mail.ph",
  "temp-mail.id",
  "temp-mail.vn",
  "temp-mail.pk",
  "temp-mail.bd",
  "temp-mail.lk",
  "temp-mail.ng",
  "temp-mail.ke",
  "temp-mail.eg",
  "temp-mail.sa",
  "temp-mail.ae",
  "temp-mail.il",
  "temp-mail.tr",
  "temp-mail.gr",
  "temp-mail.pl",
  "temp-mail.cz",
  "temp-mail.sk",
  "temp-mail.hu",
  "temp-mail.ro",
  "temp-mail.bg",
  "temp-mail.hr",
  "temp-mail.rs",
  "temp-mail.ua",
  "temp-mail.by",
  "temp-mail.kz",
  "temp-mail.uz",
  "temp-mail.tm",
  "temp-mail.kg",
  "temp-mail.tj",
  "temp-mail.ge",
  "temp-mail.am",
  "temp-mail.az",
  "temp-mail.md",
  "temp-mail.li",
  "temp-mail.ch",
  "temp-mail.at",
  "temp-mail.be",
  "temp-mail.nl",
  "temp-mail.lu",
  "temp-mail.ie",
  "temp-mail.uk",
  "temp-mail.se",
  "temp-mail.no",
  "temp-mail.dk",
  "temp-mail.fi",
  "temp-mail.is",
  "temp-mail.ca",
  "temp-mail.us",
  "temp-mail.mx",
  "temp-mail.cu",
  "temp-mail.do",
  "temp-mail.pr",
  "temp-mail.vi",
  "temp-mail.bs",
  "temp-mail.bb",
  "temp-mail.tt",
  "temp-mail.jm",
  "temp-mail.ky",
  "temp-mail.ag",
  "temp-mail.lc",
  "temp-mail.vc",
  "temp-mail.dm",
  "temp-mail.gd",
  "temp-mail.kn",
  "temp-mail.bz",
  "temp-mail.hn",
  "temp-mail.sv",
  "temp-mail.gt",
  "temp-mail.ni",
  "temp-mail.cr",
  "temp-mail.pa",
  "temp-mail.ve",
  "temp-mail.co",
  "temp-mail.ec",
  "temp-mail.pe",
  "temp-mail.bo",
  "temp-mail.py",
  "temp-mail.uy",
  "temp-mail.cl",
  "temp-mail.ar",
  "temp-mail.fk",
  "temp-mail.gf",
  "temp-mail.sr",
  "temp-mail.gy",
  "temp-mail.pf",
  "temp-mail.nc",
  "temp-mail.sb",
  "temp-mail.vu",
  "temp-mail.fj",
  "temp-mail.ws",
  "temp-mail.to",
  "temp-mail.ki",
  "temp-mail.nr",
  "temp-mail.pw",
  "temp-mail.mh",
  "temp-mail.fm",
  "temp-mail.mp",
  "temp-mail.gu",
  "temp-mail.as",
  "temp-mail.um",
  "temp-mail.vi",
  "temp-mail.pr",
  "temp-mail.do",
  "temp-mail.cu",
  "temp-mail.bs",
  "temp-mail.bb",
  "temp-mail.tt",
  "temp-mail.jm",
  "temp-mail.ky",
  "temp-mail.ag",
  "temp-mail.lc",
  "temp-mail.vc",
  "temp-mail.dm",
  "temp-mail.gd",
  "temp-mail.kn",
  "temp-mail.bz",
  "temp-mail.hn",
  "temp-mail.sv",
  "temp-mail.gt",
  "temp-mail.ni",
  "temp-mail.cr",
  "temp-mail.pa",
  "temp-mail.ve",
  "temp-mail.co",
  "temp-mail.ec",
  "temp-mail.pe",
  "temp-mail.bo",
  "temp-mail.py",
  "temp-mail.uy",
  "temp-mail.cl",
  "temp-mail.ar",
  "temp-mail.fk",
  "temp-mail.gf",
  "temp-mail.sr",
  "temp-mail.gy",
  "temp-mail.pf",
  "temp-mail.nc",
  "temp-mail.sb",
  "temp-mail.vu",
  "temp-mail.fj",
  "temp-mail.ws",
  "temp-mail.to",
  "temp-mail.ki",
  "temp-mail.nr",
  "temp-mail.pw",
  "temp-mail.mh",
  "temp-mail.fm",
  "temp-mail.mp",
  "temp-mail.gu",
  "temp-mail.as",
  "temp-mail.um",
  // Add more as needed
]);

/**
 * Validate if email is from a legitimate provider
 * Returns true if email is valid (not from disposable provider)
 */
export function isLegitimateEmail(email: string): boolean {
  try {
    const domain = email.toLowerCase().split("@")[1];
    if (!domain) return false;
    
    // Check if domain is in disposable list
    if (DISPOSABLE_DOMAINS.has(domain)) {
      return false;
    }
    
    return true;
  } catch {
    return false;
  }
}

/**
 * Get error message for disposable email
 */
export function getDisposableEmailError(): string {
  return "Sila gunakan akaun email yang sah (Gmail, Yahoo, Outlook, dll). Email sementara tidak dibenarkan.";
}
